### ISSUE TITLE
launch get_prereqs without run the test

### ISSUE THREAD

**Issue by frack113** [swimlane/atomic-operator#31]
**Is your feature request related to a problem? Please describe.**
I want to be able to set up the lab and download the requirements in advance.
But need to run the test to get them with  `get_prereqs`

**Describe the solution you'd like**
have another verb like  `set`  : `atomic-operator set --techniques T1234`

**Describe alternatives you've considered**
have of `norun` option for  `get_prereqs` : `atomic-operator run --techniques T1234 --get_prereqs --norun`

**Comment by MSAdministrator** [comment]
@frack113 Thanks for opening this one.

Are you thinking that this would be used locally and remotely? Or something else?

My initial thought was to create a new method called `get_preqs` which can be called directly and from the run command.  From the user perspective it would be like

```
atomic-operator get_prereqs --techniques T1234
```

but i'm open for other ideas too.

**Comment by frack113** [comment]
for the moment I do my tests locally. But to be able to launch the tests from a central command is surely a track to dig

**Comment by MSAdministrator** [comment]
This was added in 0.8.0 release
