### ISSUE TITLE
Logging and troubleshooting question

### ISSUE THREAD

**Issue by atomicradon** [swimlane/atomic-operator#32]
reademe says open issue for questions...  Installed on my Mac - Monterey 12.0.1. Running remote to EC2 in AWS running Windows_Server-2019-English-Full-Base-2021.12.15 AMI.  I'll occasionally get "Uknown Error's" & trying to figure out how to troubleshoot.  Not sure if it's me or a legit issue.  Console provides good info, but nothing to help with the Unknown Error.  Setting --debug True didn't help.  Can't find any logs on my Mac & takes forever to parse through powershell event logs on my target host to find anything, when I'm not sure what I'm looking for...

For example, I'll run:

atomic-operator run --atomics-path "redcanaryco-atomic-red-team-d39dc66" --techniques T1055,T1055.001,T1055.004 --hosts "1.2.3.4" --username "<UserNameHere>" --password "<PasswordHere>" --check_prereqs True

Results are T1055.001 (the last one) worked, and the rest didn't.  

1c91e740-1729-4329-b779-feba6e71d048: {"1.2.3.4": {"command": {"error": "Uknown Error - Received an unknown error from host - 1.2.3.4 - Received AttributeError"}}, "technique_id": "T1055", "technique_name": "Process Injection"}
3203ad24-168e-4bec-be36-f79b13ef8a83: {"1.2.3.4": {"command": {"error": "Uknown Error - Received an unknown error from host - 1.2.3.4 - Received AttributeError"}}, "technique_id": "T1055", "technique_name": "Process Injection"}
611b39b7-e243-4c81-87a4-7145a90358b1: {"1.2.3.4": {"command": {"error": "Uknown Error - Received an unknown error from host - 1.2.3.4 - Received AttributeError"}}, "technique_id": "T1055.004", "technique_name": "Process Injection: Asynchronous Procedure Call"}
74496461-11a1-4982-b439-4d87a550d254: {"1.2.3.4": {"command": {}}, "technique_id": "T1055.001", "technique_name": "Process Injection: Dynamic-link Library Injection"}

Appreciate any pointers you can offer

**Comment by MSAdministrator** [comment]
@atomicradon there should be logs in the package folder where atomic-operator is installed. Typically you can get to them by doing 

```pip show atomic-operator ```

This should show you the `Location` - if you ls to that location you should see logs - let me know if you don't
