### ISSUE TITLE
Installation fails on ARM-based (M1) Mac

### ISSUE THREAD

**Issue by keithmccammon** [swimlane/atomic-operator#36]
**Describe the bug**
Installing using pip3 natively may not work on an ARM-based (M1) Mac for a wide variety of reasons (Python + ARM is fraught with sadness). So, you'll probably want to build from source. 

Building from source will likely fail because of a dependency on setuptools_rust, which requires a Rust compiler. 

**To Reproduce**
1. Attempt the steps in the README
2. Receive the error: `ModuleNotFoundError: No module named 'setuptools_rust'`

**Desktop (please complete the following information):**
 - OS: macOS Monterey

**Additional context**
This public Gist contains an alternate installation script that resolves this issue: https://gist.github.com/keithmccammon/5aa831e74abb74922404289d48ed1e29

**Comment by MSAdministrator** [comment]
@keithmccammon I currently do not have a M1 to test with but thanks for the gist you provided.  Any ideas on how to solve this in the code base itself?  I would rather tackle it there than documentation but if we have to then documentation it is.

**Comment by keithmccammon** [comment]
> @keithmccammon I currently do not have a M1 to test with but thanks for the gist you provided. Any ideas on how to solve this in the code base itself? I would rather tackle it there than documentation but if we have to then documentation it is.

I see that this was closed by way of documentation, which is probably the best that you can do this moment. I do not believe that there's a workaround, given that building from source on M1 is required in many/most cases.
