### ISSUE TITLE
No results returned from atomic execution on windows

### ISSUE THREAD

**Issue by clr2of8** [swimlane/atomic-operator#45]
I just downloaded the "main" branch today and ran on Windows with the latest Python install. When I select the first test listed for this technique it returns empty results.

![image](https://user-images.githubusercontent.com/22311332/155373159-cc8c5c6e-5a8a-47c3-8c91-da0447865ccc.png)

If I try to run all T1016 atomics I get "unexpected keyword argument" again.

![image](https://user-images.githubusercontent.com/22311332/155373466-e35c4fe9-59f9-4143-bc01-99a534154544.png)

**Comment by MSAdministrator** [comment]
I’ll check this out tomorrow morning. Sorry about the problems - thought I resolved these.
