### ISSUE TITLE
Installation trouble on Ubuntu 20

### ISSUE THREAD

**Issue by clr2of8** [swimlane/atomic-operator#46]
I just installed the "main" branch today on Ubuntu, I ran pip install requirements, but I'm still having trouble running atomic-operator. It could be my error. Can you help?

![image](https://user-images.githubusercontent.com/22311332/155376274-2a0d473d-e837-415e-8a78-22a56ed63105.png)

**Comment by MSAdministrator** [comment]
@clr2of8 I believe you are in the nested folder `atomic_operator`. If you cloned the repository then you should be in the `atomic-operator` directory and then run 

```
python3 setup.py install
```

which should install everything, including the requirements, on that system.

let me know if that doesn't resolve it!

**Comment by clr2of8** [comment]
Ok, cool, that got it installed for me just fine, now I get the same issue that I got on Windows that I posted already as an issue.

![image](https://user-images.githubusercontent.com/22311332/155415297-34ed322e-17eb-40a4-a434-4222265bb945.png)
