### ISSUE TITLE
Search for tests

### ISSUE THREAD

**Issue by HackThePlanetKC** [swimlane/atomic-operator#59]
**Is your feature request related to a problem? Please describe.**
It would be fantastic to be able to search for a specific test. Currently, I'm looking through the atomics for a good test to verify RC O365 integration, but going to the Slack and searching manually is taking a long time.

**Describe the solution you'd like**
A search function like searchsploit or atomic-operator -search "$keyword"

**Describe alternatives you've considered**
Going to the official Slack channel for advice, searching through https://atomicredteam.io/atomics/ myself

**Additional context**
None at this time

**Comment by HackThePlanetKC** [comment]
I do plan on pulling a fork and trying to implement this myself, but if someone else could do it faster and better than me, go right ahead.

**Comment by MSAdministrator** [comment]
@HackThePlanetKC I am adding this feature now. Checkout #62
