### ISSUE TITLE
Remote tests with config file not working

### ISSUE THREAD

**Issue by ari-wein** [swimlane/atomic-operator#61]
**Describe the bug**
When attempting to run tests against a remote machine (Mac in this case), atomic operator appears to try to execute tests on localhost instead (Ubuntu Linux in this case). 

**To Reproduce**
Here is my command:
```
atomic-operator run --config_file ./apa/test1.yml --hosts 'IP' --username myuser --password 'super secret password' --config_file_only --debug
```
And here is the contents of the config file:
```
atomic_tests:
  - guid: b3e7510c-2d4c-4249-a33f-591a2bc83eef
  - guid: 1864fdec-ff86-4452-8c30-f12507582a93
```

And here is the output:
```
DEBUG:Base.AtomicOperator:Checking technique T1562.001 (Impair Defenses: Disable or Modify Tools) for applicable tests.
INFO:Base:You provided a test (b3e7510c-2d4c-4249-a33f-591a2bc83eef) 'Stop and unload Crowdstrike Falcon on macOS' which is not supported on this platform. Skipping...
DEBUG:Base.AtomicOperator:Checking technique T1555.001 (Credentials from Password Stores: Keychain) for applicable tests.
INFO:Base:You provided a test (1864fdec-ff86-4452-8c30-f12507582a93) 'Keychain' which is not supported on this platform. Skipping...
b3e7510c-2d4c-4249-a33f-591a2bc83eef: {}
1864fdec-ff86-4452-8c30-f12507582a93: {}
```

**Expected behavior**
Tests should execute on remote machine
Note that I have successfully executed one-off tests successfully from the command line by passing in individual test UIDs, so I know there's nothing wrong with my connection parameters.

**Comment by MSAdministrator** [comment]
Thanks for this. I will troubleshoot and get a fix in as soon as I can.

**Comment by MSAdministrator** [comment]
@ari-wein I actually just re-read this issue and when you are passing in `--config_file_only` then atomic-operator will ignore parameters that are passed in besides that config file. So your config file should have your hosts and connection details instead of being passed into atomic-operator via command line arguments. Does that make sense? This should resolve the issue.

If you run into issues, please re-open this issue
