### ISSUE TITLE
Running with config_file is not applying input argument values

### ISSUE THREAD

**Issue by rarsan** [swimlane/atomic-operator#63]
**Describe the bug**
Running with config_file is not applying custom input values, and instead uses the technique's default values.

**To Reproduce**
config.yml
```
atomic_tests:
  - guid: 9fdd83fd-bd53-46e5-a716-9dec89c8ae8e
    input_arguments:
      project-id:
        value: test-project
```

Run test locally:
```
 atomic-operator run --config_file ./config.yml --config_file_only
```

Output:
```
INFO:Base.AtomicOperator:Running Creating GCP Service Account and Service Account Key test (9fdd83fd-bd53-46e5-a716-9dec89c8ae8e) for technique T1078.004
INFO:Base.Runner:

WARNING: You do not appear to have access to project [art-project-1] or it does not exist.
ERROR: (gcloud.iam.service-accounts.create) User [<REDACTED>] does not have permission to access projects instance [art-project-1] (or it may not exist): Permission 'iam.serviceAccounts.create' denied on resource (or it may not exist).
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: iam.googleapis.com
  metadata:
    permission: iam.serviceAccounts.create
  reason: IAM_PERMISSION_DENIED
ERROR: (gcloud.iam.service-accounts.keys.create) NOT_FOUND: Unknown service account
```

Note the atomic for T1078.004 in question was slightly modified to skip the login step (since it requires a prompt) in the sequence of test commands:
```
  executor:
    name: sh
    elevation_required: false
    command: |
      #gcloud auth login --no-launch-browser
      gcloud config set project #{project-id}
      gcloud iam service-accounts create #{service-account-name}
      gcloud iam service-accounts keys create #{output-key-file} --iam-account=#{service-account-email}
```

**Expected behavior**
Expected to apply the value **test-project** for input argument `project-id`, and not the default value **art-project-1** defined in technique atomic.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**More context:**
Excerpt from [T1078.004 atomic](https://github.com/redcanaryco/atomic-red-team/blob/16594d72c5556e3a85d1a789c10419678ffce806/atomics/T1078.004/T1078.004.yaml):

```
atomic_tests:
- name: Creating GCP Service Account and Service Account Key
  auto_generated_guid: 9fdd83fd-bd53-46e5-a716-9dec89c8ae8e
  description: |
    GCP Service Accounts can be used to gain intial access as well as maintain persistence inside Google Cloud.

  supported_platforms:
  - google-workspace
  - iaas:gcp
  - linux

  input_arguments:
    project-id:
      description: ID of the project, you want to create service account as well as service account key for
      type: string
      default: art-project-1

  [...]
```

**Comment by MSAdministrator** [comment]
@rarsan Thanks for submitting this! Currently, configuring input arguments via config is not supported. I can add this but it may take a bit to do. Please feel free to submit a PR though!

**Comment by rarsan** [comment]
Thx for taking a look. So this usage example from README is invalid?
https://github.com/swimlane/atomic-operator#running-atomic-operator-using-a-config_file
Note how it specifies `input_arguments`.

This seems like a common use case. Are there suggested workarounds? Perhaps setting flags directly?

**Comment by MSAdministrator** [comment]
@rarsan Yeah the readme is wrong (I will update it). You can pass them along right now as command line parameter or a KWARGS if using the module in your code base. I am adding a way to do this via command line using a new parameter called `input_arguments` which would take a dictionary of keys and values and pass them to the technique command. This should be merged soon

**Comment by MSAdministrator** [comment]
@rarsan Actually, I think I was able to resolve this for both the command line and via config file. It will be in #62
